// <auto-generated />
namespace Win10_task1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InstallMigration4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InstallMigration4));
        
        string IMigrationMetadata.Id
        {
            get { return "202106181110535_InstallMigration4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
